In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('csv files/Housing.csv')
df

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [3]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB


In [7]:
df.shape

(545, 13)

In [8]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

In [9]:
x = pd.DataFrame(df)
x.drop(columns=['price'], inplace=True)
x

area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    7420         4          2        3      yes        no       no   
1    8960         4          4        4      yes        no       no   
2    9960         3          2        2      yes        no      yes   
3    7500         4          2        2      yes        no      yes   
4    7420         4          1        2      yes       yes      yes   
..    ...       ...        ...      ...      ...       ...      ...   
540  3000         2          1        1      yes        no      yes   
541  2400         3          1        1       no        no       no   
542  3620         2          1        1      yes        no       no   
543  2910         3          1        1       no        no       no   
544  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 12 columns]

In [11]:
y = pd.DataFrame(df['price'])
y

price
0    13300000
1    12250000
2    12250000
3    12215000
4    11410000
..        ...
540   1820000
541   1767150
542   1750000
543   1750000
544   1750000

[545 rows x 1 columns]

In [13]:
x_train, x_test,y_train, y_test = train_test_split(x,y,test_size=0.2)

In [14]:
x_train.shape

(436, 12)

In [15]:
x_test.shape

(109, 12)

In [16]:
y_train.shape

(436, 1)

In [17]:
y_test.shape

(109, 1)

In [18]:
tr = ColumnTransformer(transformers=[
    ('t1',OrdinalEncoder(categories=[['furnished','semi-furnished','unfurnished']]),['furnishingstatus']),
    ('t2',OneHotEncoder(drop='first',sparse=False),['mainroad','guestroom','basement','hotwaterheating','airconditioning','prefarea'])
], remainder='passthrough')

In [19]:
tr

ColumnTransformer(remainder='passthrough',
                  transformers=[('t1',
                                 OrdinalEncoder(categories=[['furnished',
                                                             'semi-furnished',
                                                             'unfurnished']]),
                                 ['furnishingstatus']),
                                ('t2',
                                 OneHotEncoder(drop='first', sparse=False),
                                 ['mainroad', 'guestroom', 'basement',
                                  'hotwaterheating', 'airconditioning',
                                  'prefarea'])])

In [20]:
a = tr.fit_transform(x_train)
a

array([[1., 1., 1., ..., 1., 1., 0.],
       [1., 1., 0., ..., 1., 2., 0.],
       [2., 1., 0., ..., 1., 1., 0.],
       ...,
       [1., 1., 1., ..., 1., 1., 2.],
       [0., 1., 1., ..., 1., 2., 1.],
       [0., 1., 0., ..., 2., 3., 2.]])

In [21]:
b = tr.fit_transform(x_test)
b

array([[1., 1., 0., ..., 1., 2., 1.],
       [0., 1., 0., ..., 1., 1., 2.],
       [2., 0., 0., ..., 2., 2., 0.],
       ...,
       [1., 1., 0., ..., 1., 4., 2.],
       [2., 1., 0., ..., 1., 1., 2.],
       [1., 1., 0., ..., 1., 2., 2.]])

In [22]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [23]:
lr.fit(a, y_train)

LinearRegression()

In [24]:
lr.predict(b)

array([[4376705.80509731],
       [6113385.26133844],
       [3426099.38284921],
       [6227786.81177418],
       [3469158.00607782],
       [5190595.09397112],
       [5964495.5795305 ],
       [5111940.73754051],
       [3759620.45469761],
       [6262108.67151379],
       [5340753.40461894],
       [4411226.18494402],
       [3063439.27423148],
       [5345914.74372688],
       [5754055.3598325 ],
       [3659001.14487057],
       [6632266.28552522],
       [4718190.5943331 ],
       [4626696.61217701],
       [6609517.57985405],
       [4329014.77602312],
       [4049972.3468952 ],
       [2948275.30248851],
       [7680425.22158136],
       [6664730.00083595],
       [7877142.28333012],
       [6042407.95238135],
       [3566142.88597382],
       [4021242.49866627],
       [5685892.35376635],
       [3518324.52148123],
       [3452576.64897636],
       [5941038.15570422],
       [8352552.29329048],
       [6173102.01724658],
       [4016460.39282902],
       [6927634.93764694],
 

In [25]:
lr.score(a, y_train)

0.6800254712923498

In [26]:
lr.score(b, y_test)

0.6669702403808164