# Scalar
A Scalar is a quantity which is described by a numerical value. It is used to represent values such as:
*	A number like 50
*	Mass of sun in kilograms 
*	Length of the great wall of china in kilometres

In [1]:
# Define scalars
number_of_units = 50
mass_of_sun = 1.989e30
length_great_wall_of_china = 21196
print(number_of_units)
print(mass_of_sun)
print(length_great_wall_of_china)

50
1.989e+30
21196


# Vector
A vector is an ordered collection of scalars. It can be represented in two forms:
*	Column vector: Contains n rows and 1 column
*	Row vector: Contains 1 row and n columns

The number of scalars in a vector is called its dimension or order.

In [2]:
# importing required library (numpy as np)
import numpy as np
# creating a column vector with 2 rows and 1 column using np.array() function
col_vec = np.array([[4],[3]])
print ("A column vector\n",col_vec)
# printing the shape of the vector
print("Shape of vector=",col_vec.shape)

A column vector
 [[4]
 [3]]
Shape of vector= (2, 1)


In [3]:
# importing required library (numpy as np)
import numpy as np
# creating a row vector with 1 row and 3 columns using np.array() function
row_vec = np.array([[4,-1,2]])
print("A row vector\n",row_vec)
# printing the shape of the vector
print("Shape of vector=",row_vec.shape)

A row vector
 [[ 4 -1  2]]
Shape of vector= (1, 3)


In [4]:
# importing required library (numpy as np)
import numpy as np
#Illustrating a Zero row vector of dimension 3 using np.array() function
zero_vector_1=np.array([0,0,0])
print(zero_vector_1)
#Illustrating a Zero row vector of dimension 3 using np.zeros() function
zero_vector_2=np.zeros(3)
print(zero_vector_2)
#Illustrating a Zero column vector of dimension 3 using np.zeros() and reshape() function
zero_vector_3=np.zeros(3).reshape(3,-1)
print(zero_vector_3)

[0 0 0]
[0. 0. 0.]
[[0.]
 [0.]
 [0.]]


In [5]:
# importing required library (numpy as np)
import numpy as np
#Illustrating a One vector of dimension 3 using np.array() function
one_vector_1=np.array([1,1,1])
print(one_vector_1)
#Illustrating a One vector of dimension 3 using np.ones() function
one_vector_2=np.ones(3)
print(one_vector_2)
#Illustrating a column vector of ones of dimension 3 using np.ones() and reshape() function 
one_vector_3=np.ones(3).reshape(3,-1)
print(one_vector_3)


[1 1 1]
[1. 1. 1.]
[[1.]
 [1.]
 [1.]]


In [6]:
# Indexing
# importing required libraries (numpy as np)
import numpy as np
vector=np.array([[4],[-1],[2]])
print("The vector\n",vector)
#Addressing a value of vector by index
print("\nElement at position 1=",vector[1])

The vector
 [[ 4]
 [-1]
 [ 2]]

Element at position 1= [-1]


In [7]:
# Magnitude and direction of a vector
# importing required libraries (numpy as np)
import numpy as np
#Create a vector
vector=np.array([3,3])
#Magnitude of vector can be found using function np.linalg.norm() function
print("\nMagnitude of the vector = ",np.linalg.norm(vector))


Magnitude of the vector =  4.242640687119285


In [8]:
# Matrix
# importing required libraries (numpy as np)
import numpy as np
# Creating matrices of various dimension using np.array() function
matrix_2x2 = np.array([[1, 2], 
                       [3, 4]])
matrix_3x3 = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [8, 9, 10]])
print("2x2 Matrix\n",matrix_2x2,"\nshape of matrix -> ",matrix_2x2.shape)
print("\n3x3 Matrix\n",matrix_3x3,"\nshape of matrix -> ",matrix_3x3.shape)

2x2 Matrix
 [[1 2]
 [3 4]] 
shape of matrix ->  (2, 2)

3x3 Matrix
 [[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]] 
shape of matrix ->  (3, 3)


In [9]:
# Accessing elements of a matrix
# importing required libraries (numpy as np)
import numpy as np
# Creating a 3x2 Matrix "A"
A = np.array([[2,-2],[3,1],[1,4]])
#selecting an element at row index 2 and column index 1
print("Element of matrix A at index position [2,1] is", A[2,1])

Element of matrix A at index position [2,1] is 4


In [10]:
# Transpose of a matrix
# importing required libraries (numpy as np)
import numpy as np
# Creating a 3x2 Matrix "A"
A = np.array([[2,-2],[3,1],[1,4]])
print("Matrix A:\n",A)
# Finding transpose of a matrix using the function transpose()
print("Matrix A Transpose: \n",np.transpose(A))

Matrix A:
 [[ 2 -2]
 [ 3  1]
 [ 1  4]]
Matrix A Transpose: 
 [[ 2  3  1]
 [-2  1  4]]


# Types of Matrices
Matrices can be categorized on the basis of the value of their elements, position of elements,  number of rows and columns, etc. as follows:

* Diagonal matrix
* Identity matrix
* Symmetric matrix
* Triangular matrix

In [12]:
# importing required libraries (numpy as np)
import numpy as np
# Creating a diagonal matrix with diagonal elements as (1,3,2)
diagonal_matrix = np.diag((1,3,2))
print(diagonal_matrix)
# Creating a diagonal matrix with a range of values
matrix_range= np.diag(np.arange(1,6,2))
print(matrix_range)

[[1 0 0]
 [0 3 0]
 [0 0 2]]
[[1 0 0]
 [0 3 0]
 [0 0 5]]


In [13]:
# importing required libraries (numpy as np)
import numpy as np
#Creating an Identity matrix of size 2 using np.identity() function
identity_matrix_1 = np.identity(2)
print("Identity_matrix 1\n",identity_matrix_1)
#Creating an Identity matrix of size 3 using np.eye() fucntion
identity_matrix_2 = np.eye(3)
print("\nIdentity_matrix 2\n",identity_matrix_2)

Identity_matrix 1
 [[1. 0.]
 [0. 1.]]

Identity_matrix 2
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
# importing required libraries (numpy as np)
import numpy as np
#Creating matrix A
A = np.array([[2,3,1],
            [3,4,-1],
            [1,-1,1]])
print("A:\n" , A)
# Finding the Transpose of the matrix
transposed_matrix = A.transpose()
print("Transpose of A:\n" , transposed_matrix)
#Comparing each element of both matrices (returns a matrix of boolean compared values) and saving it in a variable comparison
comparison = (A == transposed_matrix)
#Checking if all the elements in the matrix comparision is true
equal_arrays = comparison.all()
print(equal_arrays)

A:
 [[ 2  3  1]
 [ 3  4 -1]
 [ 1 -1  1]]
Transpose of A:
 [[ 2  3  1]
 [ 3  4 -1]
 [ 1 -1  1]]
True


In [15]:
# importing required libraries (numpy as np)
import numpy as np
#Creating a lower triangular matrix
lower_triangular_matrix_1 = np.tril([[1,2,3],
                               [4,5,6],
                               [7,8,9]])
print("Lower triangular matrix\n",lower_triangular_matrix_1)

Lower triangular matrix
 [[1 0 0]
 [4 5 0]
 [7 8 9]]


In [16]:
# importing required libraries (numpy as np)
import numpy as np
#Creating a Upper triangular matrix
upper_triangular_matrix_1 = np.triu([[1,2,3],
                               [4,5,6],
                               [7,8,9]])
print("Upper triangular matrix\n",upper_triangular_matrix_1)

Upper triangular matrix
 [[1 2 3]
 [0 5 6]
 [0 0 9]]


In [17]:
# Vectors
# importing required libraries (numpy as np)
import numpy as np
#Create 2 vectors
vector_1 = np.array([[2, -1, 1]]) 
vector_2 = np.array([[1, 2, -1]]) 
   
print ("1st  Vector :  ", vector_1)  
print ("2nd  Vector :  ", vector_2)  
# Addition of the vectors using the function np.add()
out = np.add(vector_1, vector_2)  
print ("Added Vector : ", out)

1st  Vector :   [[ 2 -1  1]]
2nd  Vector :   [[ 1  2 -1]]
Added Vector :  [[3 1 0]]


In [18]:
# Vector Addition
# importing required libraries (numpy as np)
import numpy as np
#Create 2 vectors
vector_1 = np.array([[2, -1, 1]]) 
vector_2 = np.array([[1, 2, -1]]) 
   
print ("1st  Vector :  ", vector_1)  
print ("2nd  Vector :  ", vector_2)  
# Addition of the vectors using the function np.add()
out = np.add(vector_1, vector_2)  
print ("Added Vector : ", out)

1st  Vector :   [[ 2 -1  1]]
2nd  Vector :   [[ 1  2 -1]]
Added Vector :  [[3 1 0]]


In [19]:
# Matrix Addition
# importing required libraries (numpy as np)
import numpy as np
# Creation of 2 matrices
matrix_1 = np.array([[10,20,30],
                     [-30,-40,-50]]) 
matrix_2 = np.array([[100,-200,300],
                     [30,50,70]]) 
   
print ("1st  Matrix : \n", matrix_1)  
print ("2nd  Matrix : \n", matrix_2)  
# Addition of the matrices using np.add() function
out = np.add(matrix_1, matrix_2)  
print ("Added Matrix : \n", out)

1st  Matrix : 
 [[ 10  20  30]
 [-30 -40 -50]]
2nd  Matrix : 
 [[ 100 -200  300]
 [  30   50   70]]
Added Matrix : 
 [[ 110 -180  330]
 [   0   10   20]]


In [20]:
# Multiplication of Vector by a Scalar
# importing required libraries (numpy as np)
import numpy as np
#Defining a Vector 'v' and scalar 's'
v = np.array([[2],[-1],[3]])
s = 2.5 
#Scalar Vector Multiplication
vector_mul = v*s 
print("Vector: \n",v,"\nScalar:",s,"\nScalar Vector multiplication:\n",vector_mul)

Vector: 
 [[ 2]
 [-1]
 [ 3]] 
Scalar: 2.5 
Scalar Vector multiplication:
 [[ 5. ]
 [-2.5]
 [ 7.5]]


In [21]:
#Multiplication of Matrix by a Scalar
# importing required libraries (numpy as np)
import numpy as np
#Defining a matrix 'A' and scalar 's'
A = np.array([[1,2,1],
                     [-1,1,0],
                     [2,-1,1]])
print("Matrix:\n",A)
s = 2.5
print("Scalar :",s)
#Multiplication of Matrix by a Scalar
matrix_mul =  s * A
print("Multiplication of Matrix by a Scalar:\n",matrix_mul)

Matrix:
 [[ 1  2  1]
 [-1  1  0]
 [ 2 -1  1]]
Scalar : 2.5
Multiplication of Matrix by a Scalar:
 [[ 2.5  5.   2.5]
 [-2.5  2.5  0. ]
 [ 5.  -2.5  2.5]]


In [22]:
#Orthogonal vectors : If the inner product of two non-zero vectors v1 and v2 is zero, that is
#then, the vectors v1 and v2 are called orthogonal vectors.
# importing required libraries (numpy as np)
import numpy as np
#Creating vectors
Vector_1 = np.array([[3],[-1],[2]])
Vector_2 = np.array([[2],[4],[-1]])
print("Vector 1\n",Vector_1)
print("Vector 2\n",Vector_2)
#Finding the transpose of Vector_1 
trans = np.transpose(Vector_1)
#Finding the dot product 
result = np.dot(trans,Vector_2)
print("Dot Product\n",result)

Vector 1
 [[ 3]
 [-1]
 [ 2]]
Vector 2
 [[ 2]
 [ 4]
 [-1]]
Dot Product
 [[0]]


In [23]:
# Matrix - Vector Multiplication
#import the library numpy
import numpy as np
#Define a matrix
A =  np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("A :\n", A)
#Define a column vector
v = np.array([[1], [2], [3]])
print("v :\n", v)
# Find product of the matrix and Vector
product = np.matmul(A,v)
print("Product of A and v is: \n", product)

A :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
v :
 [[1]
 [2]
 [3]]
Product of A and v is: 
 [[14]
 [32]
 [50]]


In [24]:
# importing numpy library
import numpy as np	
# create numpy 2d-array	
m = np.array([[1, 2],[2, 3]])
print("Printing the Original square array:\n",m)
# finding eigenvalues and eigenvectors
w, v = np.linalg.eig(m)
# printing eigen values
print("Printing the Eigen values of the given square array:\n",w)
# printing eigen vectors
print("Printing Right eigenvectors of the given square array:\n",v)

Printing the Original square array:
 [[1 2]
 [2 3]]
Printing the Eigen values of the given square array:
 [-0.23606798  4.23606798]
Printing Right eigenvectors of the given square array:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [25]:
import numpy as np
y = np.array([1, 2, 4, 7, 11, 16], dtype=np.float)
j = np.gradient(y)
y
j

C:\Users\CS-L1-PC13\AppData\Local\Temp\ipykernel_9596\53784428.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y = np.array([1, 2, 4, 7, 11, 16], dtype=np.float)


array([1. , 1.5, 2.5, 3.5, 4.5, 5. ])