# Lee decides to walk 10000 steps everyday to combat the effect that lockdown has had on his body's agility, mobility, flexibility and strength. Consider the following data from fitness tracker over a period of 10 days.

## Represent the above data in a 10x2 array. In each row, the first element should contain a day number and second element should contain steps walked.

In [2]:
import numpy as np
#Creating a 2D array
Day_number = np.arange(1, 11)
Steps_walked = [6012, 7079, 6886, 7230, 4598, 5564, 6971, 7763, 8032, 9569]
arr = np.array([Day_number, Steps_walked])
arr = arr.T
arr

array([[   1, 6012],
       [   2, 7079],
       [   3, 6886],
       [   4, 7230],
       [   5, 4598],
       [   6, 5564],
       [   7, 6971],
       [   8, 7763],
       [   9, 8032],
       [  10, 9569]])

## Lee notices that the tracker's battery dies every day at 7 pm. Lee discovers that on an average, he walks 2000 steps every day after 7 pm. Perform an appropriate operation on your array to add 2000 steps to all the observations.

In [3]:
new_arr = arr[:,1] + 2000
arr[:,1] = new_arr
arr

array([[    1,  8012],
       [    2,  9079],
       [    3,  8886],
       [    4,  9230],
       [    5,  6598],
       [    6,  7564],
       [    7,  8971],
       [    8,  9763],
       [    9, 10032],
       [   10, 11569]])

## Write a program that returns the steps walked if the steps walked are more than 9000.

In [4]:
matched = arr[:,1] > 9000
matched 
new_arr = arr[matched]
new_arr

array([[    2,  9079],
       [    4,  9230],
       [    8,  9763],
       [    9, 10032],
       [   10, 11569]])

## Print an array containing steps walked in sorted order.

In [5]:
sortedArr = arr[arr[:,1].argsort()]
print('Sorted 2D Numpy Array')
print(sortedArr)

Sorted 2D Numpy Array
[[    5  6598]
 [    6  7564]
 [    1  8012]
 [    3  8886]
 [    7  8971]
 [    2  9079]
 [    4  9230]
 [    8  9763]
 [    9 10032]
 [   10 11569]]
