# NumPy

NumPy is a Numerical Python library to create and manipulate multidimensional arrays useful in data science.

# Exercise 1: Create 4x2 integer array and prints its attributes 

In [2]:
import numpy
array1 = numpy.empty([4,2], dtype = numpy.uint16)
print("Printing Array")
print(array1)
print("Printing numpy array attributes")
print("1> Array shape is: ", array1.shape)
print("2> Array dimensions are: ", array1.ndim)
print("3> Length of each element of array in bytes is: ", array1.itemsize)

Printing Array
[[61061 38518]
 [51756 53326]
 [27614 58910]
 [19582 60791]]
Printing numpy array attributes
1> Array shape is:  (4, 2)
2> Array dimensions are:  2
3> Length of each element of array in bytes is:  2


# Exercise 2: Create a 5x2 array from a range between 100 to 200 such that the difference between each element is 10

In [3]:
import numpy 
print("Creating 5x2 array using numpy.arange")
sampleArray = numpy.arange(100, 200, 10)
sampleArray = sampleArray.reshape(5, 2)
print(sampleArray)

Creating 5x2 array using numpy.arange
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


# Exercise 3: Following is the provided numpy array. Return array of items by taking the third column from all rows

In [4]:
import numpy 
sampleArray = numpy.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])
print("Printing Input Array")
print(sampleArray)

print("\nPrinting array of items in the third column from all rows")
newArray = sampleArray[...,2]
print(newArray)

Printing Input Array
[[11 22 33]
 [44 55 66]
 [77 88 99]]

Printing array of items in the third column from all rows
[33 66 99]


# Exercise 4: Return array of odd rows and even columns from below numpy array

In [6]:
import numpy
sampleArray = numpy.array([[3,6,9,12], [15,18,21,24], [27,30,33,36], [39,42,45,48], [51,54,57,60]])
print("Printing Input Array")
print(sampleArray)

print("\nPrinting array of odd rows and even columns")
newArray = sampleArray [::2, 1::2]
print(newArray)

Printing Input Array
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]

Printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 60]]


# Exercise 5: Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element

In [7]:
import numpy

arrayOne = numpy.array([[5,6,9], [21,18,27]])
arrayTwo = numpy.array([[15,33,24], [4,7,1]])                                         

resultArray = arrayOne + arrayTwo
print("Addition of two arrays is \n")
print(resultArray)

for num in numpy.nditer(resultArray, op_flags = ['readwrite']):
    num[...] = num*num
print("\nResult array after calculating the square root of all elements\n")
print(resultArray)

Addition of two arrays is 

[[20 39 33]
 [25 25 28]]

Result array after calculating the square root of all elements

[[ 400 1521 1089]
 [ 625  625  784]]


# Exercise 6: Split the array into four equal-sized sub-arrays 

In [8]:
import numpy 

print("Creating 8x3 array using numpy.arange")
sampleArray = numpy.arange(10, 34, 1)
sampleArray = sampleArray.reshape(8, 3)
print(sampleArray)

print("\nDividing 8x3 array using numpy.arange")
subArrays = numpy.split(sampleArray, 4)
print(subArrays)

Creating 8x3 array using numpy.arange
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

Dividing 8x3 array using numpy.arange
[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


# Exercise 7: Sort following NumPy array

Case 1: Sort array by the second row

Case 2: Sort the array by the second column

In [11]:
import numpy

print("Printing Original array")
sampleArray = numpy.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
print(sampleArray)

sortArrayByRow = sampleArray[:, sampleArray[1, :].argsort()]
print("Sorting Original array by second row")
print(sortArrayByRow)

print("Sorting Original array by second column")
sortArrayByColumn = sampleArray[sampleArray[:,1].argsort()]
print(sortArrayByColumn)

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Sorting Original array by second row
[[73 43 34]
 [12 22 82]
 [66 94 53]]
Sorting Original array by second column
[[82 22 12]
 [34 43 73]
 [53 94 66]]


# Exercise 8: Print max from axis 0 and min from axis 1 from the following 2-D array

In [12]:
import numpy

print("Printing Original array")
sampleArray = numpy.array([[34,43,73], [82,22,12], [53,94,66]])
print(sampleArray)

minOfAxisOne = numpy.amin(sampleArray, 1)
print("Printing a min of Axis 1")
print(minOfAxisOne)

maxOfAxisOne = numpy.amax(sampleArray, 0)
print("Printing a max of Axis 0")
print(maxOfAxisOne)

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Printing a min of Axis 1
[34 12 53]
Printing a max of Axis 0
[82 94 73]


# Exercise 9: Delete the second column from a given array and insert the following new column in its place.

In [1]:
import numpy

print("Printing Original array")
sampleArray = numpy.array([[34, 43,73],[82,22,12],[53,94,66]])
print(sampleArray)

print("Array after deleting column 2 on axis 1")
sampleArray = numpy.delete(sampleArray, 1, axis=1)
print(sampleArray)

arr = numpy.array([[10,10,10]])

print("Array after inserting column 2 on axis 1")
sampleArray = numpy.insert(sampleArray, 1, arr, axis=1)
print(sampleArray)

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]


# Exercise 10: Create two 2-D aarays and plot them using Matplotlib

In [2]:
import numpy
print("Printing Original array")
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)

print("Array after deleting column 2 on axis 1")
sampleArray = numpy.delete(sampleArray, 1, axis=1)
print(sampleArray)

arr=numpy.array([[10,10,10]])

print("Array after inserting column 2 on axis 1")
sampleArray = numpy.insert(sampleArray, 1, arr, axis=1)
print(sampleArray)

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]
